
data:
  dim: 16
  train:
    samples: 10_000
  test:
    samples: 2_000
  validation:
    samples: 2_000

model:
  hidden_layers: 2
  hidden_size: 100

train:
  accelerator: gpu
  gpus: 1
  epochs: 1000
  batch_size: 32
  lr: 0.001
  seed: -1