
data:
  dim: 16
  train:
    samples: 10_000
  test:
    samples: 2_000
  validation:
    samples: 2_000

model:
  hidden_layers: 2
  hidden_size: 100

train:
  accelerator: gpu
  gpus: 1
  epochs: 100
  batch_size: 32
  lr: 0.001
  seed: -1
  checkpoint: false

clearml:
  project: template
  task: template-training
  output_uri: s3://s3.galatolo.xyz:443/clearml
  model_upload: false
  tags: 

log:
  clearml: false